### ISSUE TITLE
Server imcompatability

### ISSUE THREAD

**Issue by Noaaan** [DaFuqs/StarrySky#1]
Crashlog from server. Only running Starry Skies and Mythic Metals + dependencies.
Seems your mixin does not work on server
![image](https://user-images.githubusercontent.com/4163353/101999382-bf024200-3cdc-11eb-9bcc-712cb4759aca.png)

**Comment by DaFuqs** [comment]
Yeah, exactly what you said. That's what I'll get for always testing with OpenToLan.
