### ISSUE TITLE
The game could not be started

### ISSUE THREAD

**Issue by BlunderG** [DaFuqs/StarrySky#16]
When the "Play" button is clicked, the game loads and after the installation is finished, **it closes Minecraft Launcher and game.**

My English is not very good. I do not know the meaning of the word "Reproduce". When I wrote in the translation, it told me something like "remake". There isn't much you need to do to make this error. Go to version 1.16.5, you need to have the mods **"fabric-api-0.30.0 + 1.16"** and **"starryskies-1.0.8-1.16.5"** downloaded. Maybe you can turn on "keep the launcher open while game is running" option for the launcher. Done! I didn't do anything else, it's a replica.

The game will load and **shut itself down with the launcher** **in an instant**. Maybe you may not even notice.

No screenshot. And hey! How can i take a screenshot the game when no game?
[crash-2021-02-17_22.17.32-client.txt](https://github.com/DaFuqs/StarrySky/files/5998455/crash-2021-02-17_22.17.32-client.txt)

**Comment by DaFuqs** [comment]
The error seems to stem from the entries in the starry sky config.

May it be that the config entry "starrySkyPortalFrameBlock" reads "packed_ıce" instead of "packed_ice"? (different "i")

**Comment by BlunderG** [comment]
Here is config file sentences you mentioned:

{ 
	/* 
	   The block the portal to the Starry Sky dimension needs to be built with.
	   Build it like a nether portal & has to be activated with flint & steel
	   Default: PACKED_ICE
	*/
	"starrySkyPortalFrameBlock": "PACKED_ICE",

**Comment by DaFuqs** [comment]
I've created a completely new Minecraft 1.16.5 instance with just "fabric-api-0.30.0 + 1.16" and "starryskies-1.0.8-1.16.5" and it runs perfectly fine.
If you want to you can upload your minecraft folder somewhere and I can have a closer look at it. Or maybe just deleting the config folder may work.

**Comment by DaFuqs** [comment]
Should be fixed with 1.0.9
