### ISSUE TITLE
[BUG?] Starry skies removing nether & end registry 

### ISSUE THREAD

**Issue by profjb58** [DaFuqs/StarrySky#18]
**Describe the bug**
Hope u don't mind if I just use a screen capture :P

**Details**
Happened on the Creative Tiny Tater Test server: https://github.com/The-Tiny-Taters/TTT-Creative
  
![image](https://user-images.githubusercontent.com/46009144/113479761-bd75a900-9488-11eb-8dfc-cc648e3031be.png)

**To Reproduce**
Not entirely sure, think you mentioned it was related to: https://bugs.mojang.com/browse/MC-197860 though

**Comment by DaFuqs** [comment]
I will take a closer look at it, sure. :)

**Comment by profjb58** [comment]
Think this is related to
https://github.com/FabricMC/fabric/pull/1293

**Comment by DaFuqs** [comment]
Yeah, this is resolved with 1.17.
