### ISSUE TITLE
[Feature] Multiplatform Support

### ISSUE THREAD

**Issue by Brittank88** [DaFuqs/StarrySky#19]
Yes, yes, this is a "will this be ported to Forge" question. I usually wouldn't bother asking this, because I understand that it is potentially difficult and time-consuming to do such a thing, and then release updates for both loaders. I also know it's annoying when people keep asking.

I guess I'm just asking this time so I can at least see what your stance on doing so is. I hope I don't come across as annoying.

What this mod does is something I've been hoping to see in recent versions for literally years. It was a shame to see it only available on Fabric, simply because many other mods I love exist only on Forge.

There are some tools available to make developing for both loaders easier, such as [Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-forge), and I implore you to at least consider it. However, I understand if the answer is no - I just thought I should ask. Thanks for your time!

**Comment by DaFuqs** [comment]
I appreciate you asking, no problem.

I'm not personally opposed to a forge port on a personal standpoint (I created small forge mods for 1.7.10 before). Thing is, I mainly mod to play those mods on my own and am currently not playing any Forge packs myself.
It's a very nieche mod, but if there is huge demand I will definitely consider it and will take a closer look at Architectury API as soon as MC 1.17 is released (lots of new blocks and structires to play around with plus the configurable world height will be a game changer!)

I will leave this open as a reminder as soon as I pick up working on Starry again, once 1.17 is released. There will be no packports, though.

**Comment by Brittank88** [comment]
I appreciate the response. This is the sort of mod I wouldn't see myself playing with 8239456 other mods anyways, so no backport is okay with me.

You are approaching 50k downloads - I am not sure this is as niche as you think! 😜

**Comment by DaFuqs** [comment]
I've looked at how much work it would be to port this mod to forge and it looks like it would be pretty much a total rewite of the mod, taking weeks.
Architectury does not have the needed hooks (yet) and patchwork would only help load a forge variant on fabric.

I can see the appeal, but that's a LOT of work that I would not enjoy because I have no interest in the forge ecosystem as-is currently. I'm sorry.

**Comment by Brittank88** [comment]
I totally get it! It's a lot of work to port a mod - I wish there was some easier way!
