### ISSUE TITLE
Incompat with Mythic Metals for 1.17

### ISSUE THREAD

**Issue by Noaaan** [DaFuqs/StarrySky#20]
Hey!
I am letting you know that due to major refactors Mythic Metals 0.10.0 will be incompatible with Starry Skies. For the initial port I would recommend commenting out most of the code until I push the new source code.
Main changes are removal of many ores and adding a few new variants of existing ones. I have plans to add a few more ores
You should not have to worry about existing ores being replaced by air, as that is handled in my `DefaultedRegistryMixin`

Let me know if you want any specific information. I estimate that in a couple of weeks I will have an alpha version up on CurseForge.

**Comment by DaFuqs** [comment]
Hi Noaaan, you are a godsend! :)
As chance would have it, I'm updating all mods to 1.17 this week. Starry's world gen is pretty robust. If a certain block does not exist, the resulting sphere will not be registered at all. So don't worry about breaking anything on my side.

It would be great to have an overview over the rarity, cluster sizes and dimensions of all ores, if you will have one. Or info about more fancy generators, if you are aiming for them. Like your ocean ores from 1.16.
That said, I found your code pretty self-explanatory with everything in one place, so getting that data should not be a problem either way.

If you have special wishes (like don't generate some ores in Starry dimensions at all) I can incorporate it, pretty sure.

**Comment by DaFuqs** [comment]
The current new ore blocks and generation data for me as reference (check ingame before implementation):

Ore | VeinSize | PerChunk | Bottom | Top | DiscardChanceAir | Dimension | Variants | Comment
-- | -- | -- | -- | -- | -- | -- | -- | --
adamantite | 5 | 1 | -52 | 12 | 0,125 | overworld | stone, deepslate |
aquarium | 9 | 4 | 39 | 63 | 0 | overworld | stone | ocean only
banglum | 6 | 3 | 38 | 52 | 0,25 | overworld | stone |  
carmot | 4 | 3 | 16 | 32 | 0 | overworld | stone |  
manganese | 9 | 2 | 28 | 48 | 0,25 | overworld | stone |  
midas_gold | 6 | 7 | 10 | 128 | 0,125 | nether | netherrack |  
mythril | 4 | 1 | -36 | 16 | 0,125 | overworld | stone, deepslate |  
orichalcum | 4 | 1 | 8 | 24 | 0,125 | overworld | stone, tuff, smooth_basalt_deepslate |  
osmium | 6 | 5 | 20 | 40 | 0,25 | overworld | stone |  
palladium | 4 | 2 | 16 | 40 | 0 | nether | netherrack |  
platinum | 6 | 2 | 8 | 32 | 0 | overworld | stone |  
prometheum | 6 | 4 | 30 | 48 | 0,25 | overworld | stone, deepslate | jungle only
quadrillum | 7 | 2 | 16 | 44 | 0,25 | overworld | stone |  
runite | 3 | 2 | 9 | 39 | 0,125 | overworld | stone |  
silver | 8 | 4 | 16 | 38 | 0,25 | overworld | stone |  
stormyx | 8 | 2 | 4 | 116 | 0,125 | nether | netherrack, blackstone |  
unobtainium | 3 | 1 | -60 | 12 | 0,5 | overworld | stone, deepslate |  
tin | 8 | 4 | 44 | 72 | 0,25 | overworld | stone |  
vermiculite | 8 | 4 | 64 | 108 | 0,25 | overworld | stone |  
kyber | 4 | 1 |   |   | 0,5 | overworld | stone |  
starrite | 4 | 1 |   |   | 0,25 | end | stone, calcite |

**Comment by Noaaan** [comment]
Nice table!
If you grabbed these stats from the MythicConfig from the 1.17 branch then it is the most up-to-date you will get.
There is one major and minor change I have made which I have not pushed yet:
Aetherium has flat out been removed, and Banglum has had its perChunk dropped to 3

**Comment by DaFuqs** [comment]
Yeah, it is from your 1.17 branch.
Thank you for the info about the other changes. I have updated the table accordingly.

Pretty stoked for the release already!

**Comment by Noaaan** [comment]
I think this might be a bit outdated. If anyone actually plays 1.17 and wants a rebalance/refactor I will PR it
