### ISSUE TITLE
The portal came out, but it couldn't get in

### ISSUE THREAD

**Issue by wfwfwfw** [DaFuqs/StarrySky#24]
**Describe the bug**
![image](https://user-images.githubusercontent.com/72644389/124382985-bd41af80-dcfc-11eb-9fd8-eb26e5705543.png)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Comment by DaFuqs** [comment]
Do you play on 1.16 or on 1.17?
I could get it to work on both versions fine. Are there any mods that also add dimensions or have to do with teleporting?Can you check your log, if this message was logged please:
"The Starry Dimensions could not be loaded. If this is your first launch this is probably related to a known vanilla bug where custom dimensions are not loaded when first generating the world. Restarting / quitting and reloading will fix this issue."

**Comment by wfwfwfw** [comment]
1.17




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月4日(星期天) 晚上8:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DaFuqs/StarrySky] The portal came out, but it couldn&#39;t get in (#24)






你玩的是1.16的还是1.17的？
我可以让它在两个版本的工作罚款。有没有也可以增加维度或者和传送有关的 mod ，可以你看看你的日志，如果这个消息被记录请：“星际次元无法加载。如果这是您的第一次启动，那么这可能与一个已知的 vanilla bug 有关，在该 bug 中，首次生成世界时没有加载自定义维度。重新启动/退出和重新加载将修复此问题。”
—

您正在接收此消息，因为您创建了该线程。
直接回复此邮件，
在 GitHub 上查看或取消订阅.

**Comment by wfwfwfw** [comment]
It's the same to go back in.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DaFuqs/StarrySky"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DaFuqs/StarrySky] The portal came out, but it couldn't get in (#24)





 
Do you play on 1.16 or on 1.17?
 I could get it to work on both versions fine. Are there any mods that also add dimensions or have to do with teleporting?Can you check your log, if this message was logged please:
 "The Starry Dimensions could not be loaded. If this is your first launch this is probably related to a known vanilla bug where custom dimensions are not loaded when first generating the world. Restarting / quitting and reloading will fix this issue."

**Comment by wfwfwfw** [comment]
This is the log I got on purpose.


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "DaFuqs/StarrySky"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DaFuqs/StarrySky] The portal came out, but it couldn't get in (#24)





 
Do you play on 1.16 or on 1.17?
 I could get it to work on both versions fine. Are there any mods that also add dimensions or have to do with teleporting?Can you check your log, if this message was logged please:
 "The Starry Dimensions could not be loaded. If this is your first launch this is probably related to a known vanilla bug where custom dimensions are not loaded when first generating the world. Restarting / quitting and reloading will fix this issue."

**Comment by DaFuqs** [comment]
Can you upload your mod list / MultiMC instance?

**Comment by wfwfwfw** [comment]
There is a mod list in the small file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DaFuqs/StarrySky"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DaFuqs/StarrySky] The portal came out, but it couldn't get in (#24)





 
Can you upload your mod list / MultiMC instance?

**Comment by DaFuqs** [comment]
Github did not attach the file to the issue. Can you upload it via your browser?

**Comment by wfwfwfw** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月5日(星期一) 中午1:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DaFuqs/StarrySky] The portal came out, but it couldn&#39;t get in (#24)






github 没有将文件附加到问题中，可以通过浏览器上传吗？

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.

**Comment by wfwfwfw** [comment]
[minecraft-exported-logs-2021-07-04T21-45-05.log](https://github.com/DaFuqs/StarrySky/files/6762456/minecraft-exported-logs-2021-07-04T21-45-05.log)
[minecraft-exported-logs-2021-07-04T21-46-39.log](https://github.com/DaFuqs/StarrySky/files/6762457/minecraft-exported-logs-2021-07-04T21-46-39.log)
