### ISSUE TITLE
[BUG] Crash with Mining Dimensions

### ISSUE THREAD

**Issue by mysteryAftermath** [DaFuqs/StarrySky#26]
**Describe the bug**
This mod crashes on startup when used with the [Mining Dimensions Mod](https://www.curseforge.com/minecraft/mc-mods/mining-dimensions-fabric)

**To Reproduce**
Install The Mining Dimensions Mod, Starry Skies, and all dependencies (Fabric API, Cloth Config API)

**Additional Information**
I believe this is caused by this mod using an older version of CustomPortalAPI, this mod is using 0.0.1-beta37, while Mining Dimensions uses 0.0.1-beta45
[Crash Report](https://pastebin.com/WgJraGjb)

**Comment by mysteryAftermath** [comment]
forgot to mention, this issue only occurs with the latest version of the mining dimension mod, the changelog for which specifically mentions updating customportalapi, downgrading the mod by one version fixes it.

**Comment by DaFuqs** [comment]
fixed in 1.3.0.
