### ISSUE TITLE
[BUG] lootcrates and starry skies are not friends

### ISSUE THREAD

**Issue by Monster-Zer0** [DaFuqs/StarrySky#27]
**Describe the bug**
crash when going into the starry skies dimension when using the mod "lootcrates"

**To Reproduce**
use starry skies with lootcrates... crash when going to dimension

**Expected behavior**
no crashy crashy

https://paste.alloffabric.com/apemiqetox.yaml

**Comment by DaFuqs** [comment]
Thank you for the report & crash log. I will take a look at it.

**Comment by DaFuqs** [comment]
I could reproduce this with newer versions of fabric api. I will get it fixed asap and will let you know. :)

**Comment by DaFuqs** [comment]
I just released Loot Crates 2.3.0 that fixes the crash for me (Using LootCrates 2.3.0, Starry Skies 1.3.0 and Fabric API 0.42.1)
https://github.com/DaFuqs/LootCrates/releases/tag/2.3.0

Please try it out and report back. Otherwise try removing mods and back to the drawing board for me!
