### ISSUE TITLE
[BUG] End Portal Generates Outside Frame

### ISSUE THREAD

**Issue by ghost** [DaFuqs/StarrySky#28]
**Describe the bug**
On completing the end portal frame, the portal has... generated outside of it. It's kinda odd to look at.

**To Reproduce**
Just build a portal frame anywhere and fill it out.

**Expected behavior**
Normal end portal spawn behaviour.

**Screenshots**
![2021-11-26_19 36 24](https://user-images.githubusercontent.com/24266948/143551558-262f4449-6013-42fb-9524-87ec0c7857b5.png)

**Comment by DaFuqs** [comment]
The End portal seems to be build weirdly. Despite not looking like it at first glance, the end portal frames have a direction property that is used to determine where the portal should be located.

![2021-12-03_11 55 53](https://user-images.githubusercontent.com/26429514/144591319-a8efd44d-419e-4919-b9f1-85f9b645366e.png)
(look at the direction of the eyes - build when standing in the middle and building all frames facing the center)

That said, in such a case vanilla would not generate a portal at all, that is on me. I will change the behavior accordingly.

**Comment by ghost** [comment]
Very interesting! Thank you for responding so quickly. :)
