### ISSUE TITLE
A way to disable individual dimensions would be nice

### ISSUE THREAD

**Issue by FewerFlaws** [DaFuqs/StarrySky#3]
I've got Starry Sky and Scary Sky configured nicely, but I would greatly prefer end portals in Starry sky to lead to the vanilla End dimension.  Is it possible to get some config options which toggle the dimensions in this mod?

**Comment by DaFuqs** [comment]
An option to disable portals (not the dimensions itself) to Starrys Nether and End will be no problem at all.

More tricky is the way back from The End, depending on what kind of modpack you are tinkering on. The end portal has no way of knowing if it should teleport you back to the vanilla Overworld or the Starry Sky, so it would always place you in the vanilla Overworld.
Or is it more like a Skyblock pack that starts in the Starry Sky and then leads to the Vanilla dimensions as part of the progression?

**Comment by FewerFlaws** [comment]
I believe Bumblezone remembers the dimension you came from upon exit, so that source might be worth checking out, though I doubt they use the same portal API.

My favourite solution is a configuration option to disable the starry sky end portal such that it doesn't generate end portal blocks in starry sky at all.  I'd also be happy with overworld & starry portals both leading to vanilla end, then portals back from the end always leading to the overworld.

The modpack I'm woring on is currently a vanilla+ base, butI'll be adding a few fantasy-themed things of my own once that's solid.  The Starry sky dimensions are accessible but not the default dimensions.  I've been enjoying playing with datapacks and resource packs to tinker with them =D

**Comment by FewerFlaws** [comment]
Oh, you've already updated.  I'll check it out.  Thanks <3

**Comment by DaFuqs** [comment]
In that case the solution I've implemented already will work perfectly for your case. I'll let you know when the next release is up - should only take a few days.

If you have a first version of the modpack I would love to check it out! :)
