### ISSUE TITLE
[BUG] End Portal Always Leads To Vanilla End

### ISSUE THREAD

**Issue by ghost** [DaFuqs/StarrySky#30]
**Describe the bug**
Despite having `"enableEndPortalsToStarryEnd": true` in the config, entering the end portal (in fact, the very same portal as featured in my screenshot in #28, if that makes any difference) leads to the vanilla End dimension.

**To Reproduce**

1. have the appropriate config option set.
2. Build an end portal and enter it.
3. `Your package was delivered to the wrong address.`

**Expected behavior**
Config option should...work as you intended it. 😋

**Screenshots**
![2021-11-26_19 46 47](https://user-images.githubusercontent.com/24266948/143553160-85b0f815-8000-42d4-899f-5bd1042aa59f.png)

**Comment by ghost** [comment]
Update: This actually only happens if the end portal was created in the starry skies equivalent of the nether dimension! I guess that makes this bug a lot less severe given that it will never be encountered in survival. Still, would be more logical if both dimensions went to the right place.

**Comment by ghost** [comment]
Separate but related question - are the end gateway portals (or whatever they're called, the ones that lead to the outer end) supposed to do nothing?

**Comment by DaFuqs** [comment]
Those are a lot of high quality issues. Thank you for reporting them.

The end gateway portals definitely used to work, too. I will take a loot at everything the next few days. :)

**Comment by DaFuqs** [comment]
Can you send me a mod list, or try just running starry & it's dependencies?
I sadly could not reproduce that issue myself.

**Comment by DaFuqs** [comment]
I could reproduce the portal behavior in Starry Nether and will change the portal behavior accordingly.
