### ISSUE TITLE
[BUG] no dragon in the normal end if it was already killed in the Starry End! Intended?

### ISSUE THREAD

**Issue by MSandro** [DaFuqs/StarrySky#31]
**Describe the bug**
If I defend the Ender Dragon in the Starry End, no dragon will spawn in the normal Vanilla End Dim. Is this intended?

**To Reproduce**
1. Travel to the Starry End
2. Kill the dragon
3. go to the Vanilla End
4. no Dragon here

**Expected behavior**
I expacted to be able to defend a second dragon.

**Comment by DaFuqs** [comment]
Definitely not intended and IIRC it used to work that way. I will take a look if it happens with Starry alone and will get it fixed, if so.

**Comment by DaFuqs** [comment]
Sorry for the last answer.
I checked just with Starry alone and I had fights in both the starry end and the vanilla one.
Do you have any mods that sound like they could interfere?
