### ISSUE TITLE
[Feature] Disable Water Glass Spheres

### ISSUE THREAD

**Issue by MSandro** [DaFuqs/StarrySky#34]
I would like to decrese the amount of flowing water on my server to prevent lags, but in Starry Sky there are many Glass Spheres filled with water and an hole at the bottom. Is there an way to disable this?
(1.17.1)

**Comment by DaFuqs** [comment]
Oh yeah, I can sense that being useful for servers without pregen

**Comment by DaFuqs** [comment]
Currently there is no way, but I should create one, in whatever way

**Comment by DaFuqs** [comment]
In 1.19.2 spheres will be completely json data driven with the ability to modify spheres via data pack, including fluid sphere holes
