### ISSUE TITLE
Better End end crystal pillars can generate above the build limit

### ISSUE THREAD

**Issue by cooloak1** [DaFuqs/StarrySky#36]
The obsidian pillars from the Better End mod can generate close enough to the build height limit to get cut off, but the crystal will still spawn at its original height. I don't know if this also happens with vanilla pillars.
Additionally, some pillars can spawn at y=0, which is less bad but still not ideal

**To Reproduce**
- Install both Starry Sky and Better End on MC 1.19
- Create a world
- Go to the Scarcy Sky and fly up to the top of the world
- If there isn't a cut-off pillar, try a new world

**Expected behavior**
To be honest, I'm not entirely sure what the ideal fix should be for this. I do have a few ideas though, feel free to choose one or do something else:
- Let the pillars generate cut off, but force the crystal to y=256
- Force the pillars downwards so that their tops never exceed y=255
- Don't generate pillars that go above y=255
- Don't generate any spheres above y~200 within the ring for the pillars to generate on
- Force all pillars to a preset y-level

![2022-08-01_17 39 23](https://user-images.githubusercontent.com/92229864/182273677-f8f90dbc-afcb-4241-bd05-09fc5281c4fe.png)

**Comment by DaFuqs** [comment]
It works pretty nicely with the vanilla end towers. That sadly is an issue that can only be fixed by the Better End devs, adjusting their tower generation, sorry.
