### ISSUE TITLE
[BUG] Potential conflict with another mod

### ISSUE THREAD

**Issue by Austin001316** [DaFuqs/StarrySky#37]
**Describe the bug**
Can not load or create a world with my modset

**To Reproduce**
Try to load or create a world

**Expected behavior**
It to load and/or create the world

Attached is the latest log upon crash

[latest.log](https://github.com/DaFuqs/StarrySky/files/9579978/latest.log)

**Comment by DaFuqs** [comment]
Biomes You Go
