### ISSUE TITLE
[BUG] 1.19.2 Ender Dragon + Exit portal do not spawn in the Normal End.

### ISSUE THREAD

**Issue by FrozenDragon0** [DaFuqs/StarrySky#38]
**Describe the bug**
Self-explanatory but essentially whenever this mod is active the Ender Dragon + Bedrock fountain in the normal End do not spawn whatsoever essentially leaving the player trapped with no way out without dying.

**To Reproduce**
1. Create a new world and Enter the End.
2. Observe and see that the Dragon + Bedrock fountain have not spawned at all.
**Expected behavior**
Dragon and the Bedrock fountain are supposed to spawn.

**Screenshots**

![2022-10-07_21 53 18](https://user-images.githubusercontent.com/18079316/194570132-22d2dd50-8377-44fa-adcf-7e53b6ad7f8b.png)

As a side note, the End Dragon fight in the Scarcy sky dimension seems to work fine without issue but for whatever reason breaks the normal End fight.

**Comment by DaFuqs** [comment]
Any other mods installed? Which version did you use?

**Comment by FrozenDragon0** [comment]
> Any other mods installed? Which version did you use?

Here's a list of mods: 
![image](https://user-images.githubusercontent.com/18079316/194678092-d1cdf099-edfe-480e-8c37-2098e8a77b1b.png)

Version I'm using is 1.19.2, I do suspect Starry skies is causing this as I took the mod out whilst testing and when the mod was taken out the dragon fight spawned in like it's supposed to, once I put the mod back in the fight bugged again.

Also Starry skies isn't on that list as I had to take it out to fix the boss fight in my Hardcore world.

**Comment by DaFuqs** [comment]
Could confirm in 1.19.2.
Vanilla (now?) only seems to save a single dragon fight without checking in what worlds it's active - last initiated dragon fight wins.
This lowkey sucks - Starry End now generates with an active end portal and does not initiate an ender dragon fight anymore.
