### ISSUE TITLE
[BUG] 1.19.2 Starry sky dimensions cause the game to indefinitely hang when Dungeon Now Loading is installed.

### ISSUE THREAD

**Issue by FrozenDragon0** [DaFuqs/StarrySky#39]
**Describe the bug**
Whenever Dungeon Now Loading is installed with this mod entering the custom dimensions causes the game to indefinitely hang after a few seconds, A.K.A Blocks don't drop, can't type in chat etc.

**To Reproduce**
1. Download and install Dungeon Now Loading, either in it's datapack or mod form.
2. Create a new world with both this mod and DNL installed.
3. Create and enter a portal to the Starry skies dimension.
4. Observe and notice that after a couple of seconds the game will indefinitely hang and stop responding to ticks.

**Expected behavior**
Game should not be hanging whilst DNL is installed and going into this dimension.

I believe the reason why this is happening is because Dungeon Now Loading is most likely trying to find it's custom structures in the Overworld Starry skies dimension but since it fails to do so it just essentially crashes the world.

**Comment by DaFuqs** [comment]
I could pretty much confirm your assumptions. This is something that the devs of Dungeon Now Loading have to account for, sorry!
