### ISSUE TITLE
[BUG] Mod Crashes the game before startup

### ISSUE THREAD

**Issue by asteroidb12** [DaFuqs/StarrySky#4]
**Describe the bug**
The game crashes when starting up with this mod

**To Reproduce**
First I had to launch minecraft with this mod in my mod list, the game doesn't load and it crashes.

**Expected behavior**
When launching the game, I expect a message box saying:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'starry_sky'!
Código de error: -1

**Screenshots**
Here's a text file and the mod list.
![Mod list](https://user-images.githubusercontent.com/68461874/103623615-30ed3600-4eed-11eb-8992-84501c8f5ef8.png)

[crash-2021-01-05_00.20.29-client.txt](https://github.com/DaFuqs/StarrySky/files/5768945/crash-2021-01-05_00.20.29-client.txt)

Please and thank you.

**Comment by DaFuqs** [comment]
Could you please try adding Cloth API 1.4.9?
Seems like an other mod is bundling it, but with the outdated version 1.2.0.

In the meantime I will improve the handling when an old version is present or remove that dependency alltogether.

**Comment by DaFuqs** [comment]
Removed Cloth API as dependency with next release.
