### ISSUE TITLE
[BUG] 1.19.2 None of the mod's custom advancements trigger.

### ISSUE THREAD

**Issue by FrozenDragon0** [DaFuqs/StarrySky#40]
**Describe the bug**
Self-explanatory, none of the mod's custom advancements for stepping on specific spheres trigger at all.

**To Reproduce**
1. Make a new world.
2. Build portal to the starry skies dimension.
3. Observe and notice that none of the advancements are triggering at all with the exception of the introductory advancements when entering all 3 dimensions for the first time.

**Expected behavior**
All the custom advancements should be triggering once the specific sphere for them has been touched.

**Comment by DaFuqs** [comment]
Fixed in next version
