### ISSUE TITLE
[Feature] Serverside-Only Support

### ISSUE THREAD

**Issue by ghost** [DaFuqs/StarrySky#41]
Maybe this would be better as a separate fork/mod (I'd be interested in attempting this!), but the ability for this mod to operate purely serverside (allowing for vanilla clients) would be fantastic!

AFAIK, dimensions and world generation are server-side, it's really only the custom portal stuff that I can think of that is causing the server to reject vanilla clients.

To keep the custom portals, adding optional support for [Polymer](https://github.com/Patbox/polymer) would work well. The client would just see the normal nether portal block, even though it's still the custom portal block from the mod.

Maybe there are also other features that would need to be adjusted/disabled, which is why I understand if this is something better destined for a fork/rewrite that you don't have to take care of. Still wanted to pitch the idea though.

**Comment by DaFuqs** [comment]
Sorry for only answering now.
Yes, the only thing that would have to be changed to make it run serverside would be the portal, I think.
If you are familiar with Polymer try it out and I'd be happy to help where I can

**Comment by ghost** [comment]
Exciting! This would be an amazing thing to have accessible to vanilla clients.

I'll look into it now - I'm sure I can figure it out + look at existing mods making use of Polymer.

If almost the entirety of ComputerCraft can be remade with Polymer (yes, really, it's insane), I'm sure this can be.

**Comment by ghost** [comment]
~~I have one question to ask - is it crucial that this mod remains built against Java 16? I'd like to upgrade that to Java 17 but I'm not sure if that was a purposeful choice for compatibility reasons.~~

I forked the wrong branch lmao

**Comment by DaFuqs** [comment]
Next version will have an option to disable generating of the portal, making using it server side only possible ✔

**Comment by ghost** [comment]
Awesome! I hoped to find some serverside-friendly portal library (because it should be possible with the help of Polymer), however, this is definitely good enough in the meantime. All I request is maybe a server-friendly way to still travel between the dimensions in survival.
