### ISSUE TITLE
Game crashBUG] Title

### ISSUE THREAD

**Issue by DarkCrystalll** [DaFuqs/StarrySky#42]
**Describe the bug**
I don't know

**To Reproduce**
I don't know

**Expected behavior**
create a new world
**Screenshots**
[minecraft-exported-crash-info-2022-11-28T14-48-58.zip](https://github.com/DaFuqs/StarrySky/files/10101189/minecraft-exported-crash-info-2022-11-28T14-48-58.zip)

**Comment by DaFuqs** [comment]
Will be fixed in the upcoming release. In the meantine disable the BYG compatibility in Starry Skies config
