### ISSUE TITLE
[Feature] Toggleable Planet Types + Disable LGBT flags

### ISSUE THREAD

**Issue by hyperdotbat** [DaFuqs/StarrySky#48]
Hey Id appreciate if we can configure the types of planet types generating in the world
Also It'd be nice if we werent forced to look at LGBT flags on wool planetoids ^^

**Comment by DaFuqs** [comment]
Starry Skies uses data packs for registering spheres, tweaking their frequency and much more. You can tweak everything how you can also adjust vanilla worldgen.

You can find the pride spheres here, for example:
https://github.com/DaFuqs/StarrySkies/tree/2.0.0-1.20.0/src/main/resources/data/starry_skies/starry_skies/spheres/pride

The wiki here on github also has lots of docs how to register more, or tweak existing ones.

**Comment by hyperdotbat** [comment]
Thanks for the quick reply btw
I love your mod, but a suggestion; dont try to push politics or agendas in any way in something like *a Minecraft mod*

**Comment by DaFuqs** [comment]
No prob!
