### ISSUE TITLE
[BUG] Crash when generating with Aether Reborn mod

### ISSUE THREAD

**Issue by bdashore3** [DaFuqs/StarrySky#5]
**Describe the bug**
When generating/loading a world with both the aether reborn and starry sky mod, it says "Preparing for world creation" then "Saving World" and then the game instantly crashes.

**To Reproduce**
Create a test instance with aether reborn, starry sky, and its dependencies. Then try creating a new singleplayer world.

**Expected behavior**
The world generates properly and I spawn in without issues.

**Crash report/log**
[Crash report](https://github.com/DaFuqs/StarrySky/files/5773826/crash-2021-01-05_22.52.15-client.txt)
[Minecraft logfile](https://github.com/DaFuqs/StarrySky/files/5773827/latest.log)

**Comment by bdashore3** [comment]
Turns out this is a problem with the Aether mod as discussed in the Fabric discord. Closing for now, but will reopen if the issue persists.

**Comment by DaFuqs** [comment]
For reference: https://github.com/devs-immortal/The-Aether/issues/77

If the Aether Fix doesn't resolve the problem I'll gladly take another look at it.

**Comment by bdashore3** [comment]
Yes, I made the PR and that did fix the world gen after building/testing.
