### ISSUE TITLE
[Feature] Option to disable glowing effect on queen bee

### ISSUE THREAD

**Issue by FewerFlaws** [DaFuqs/StarrySky#6]
Is it possible to get an option to remove the glow from the queen bee?  It doesn't match well with what I'm doing with the mod =]

**Comment by DaFuqs** [comment]
No problem at all. Just the glow or the whole "queen bee with more damage" thing?

**Comment by FewerFlaws** [comment]
Just the glow ^_^

**Comment by DaFuqs** [comment]
Well, now I've added an option but am not even sure if I should remove the glowing completely. It really does seem off. 🤔

**Comment by FewerFlaws** [comment]
Perhaps a custom texture or model would work?  The problem with the glow is that its visible through blocks.  A bit of flair on a queen be is well warranted =]
